travis:
  secure:
    BINSTAR_TOKEN: i56onYuOqhSvPXweaNFdI3CDpAbauy2bjNo+ONLohI9w8aNlpz+ZZpAVXLROs2wwmF7i5uOprbR7hnqwaRsVAM1q4B/JgvciaQJROSIDkhdJhTvFbcNxaSCXycBak+lGnVEM438CuUe3PXM2ivUmF19VCeZ0ZNbR/UoqLTsOWU2ig3C3Z4O0q75NsrTZAApNpzKxGANOgTaYCeFbQUVQjxD8aw+qgSu6pOFXCNbE7LcOsCAhwHzKh0l+9N8xr1WqSbuIHdZHiYCOvnwgEA+uwMmZRTrU0JdNSB/bpqHkMXjZEDhPiwd8b6XJMoLhrp/dn0jKNhoDbxCdQtGaSedkM67vv/3KF0llVYwJgHz7se9CK++39nPPFcbv3ajou73f+cowFxyW8Jari1XmzgM599MTfrvPy997oGE5Et/GazZ8R7Q9hJS5yfvnh/0EdbhqR3BmKP6WrYPyMVO9WurUrS3oIF7jV2ZzRYjvf5HMASUg40xY5X2of7FcjgnpsLzb0/7q+tBHdd4Crv1Sb30bdFG2n0PEvLckhZE8rc05/xdmeVH7NSfLZAMp7bRiFXOrrGjQDQgbSGEyC20Y7XCq1FXwHopjcAF434CEGbqmrsy/fsgfhKBBzdBBNADI2HWeU3s5N7txpeP0uvcTC8ZS+azZWjDpVROQ98/xgv72RNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
