travis:
  secure:
    BINSTAR_TOKEN: HUIvKxTtRz6upxLBz+8rEqrcJeAvnasLwPZJ+gBZro2iydtoal4UTsWv54DXLmsRuS6Ece/X4fXptWaTbmNteT+6waKo5SfPw4Z3jySpl7uosAbCnJu+8SWkzGtYNVpukEkSjr0eDfcyfW0nTMxtWcxq0vpRwC5sPtDIFKgvaj6RKOXI3790mm5zotWzxt/eVjRoGbeEzbnG8pflqt4wEAdtavCeH2h63ri3e3t7ElZskXgRZREHTOT9yuB510Qn6QS6TUMYGlsn46ru8PYnSQUtIACJQRP+NA128RSO6Yv2bk4ZCbu1tAJrk6gCO4oELQ3BMo70XfMX23u5kW8aEtwK2O06DziDcMB4iQCQYlo02XyQXksCY8EftcXhDXKgNRwJUCk3bGZiztRi6AKN2+ex9xHxSnFYPKae2aK+g0jsMhD+V/YCSbEuzWen88//vz/8DJMk0sBhn8LRcYkADNvbM41ggIdpUSAfUSMvmvS0bnZTmXRmjM/AAqqEepj8rTTJ3lkfv/veZizaRlRJztlOB9mQmFs09ElMAzEcxrQkjy+NAonCqPqftA6L51bjgaE1BdE8uUB9I2q5fjHmrwODSO4bPHzsE2vgWjvfTeK0WoQKP8j5+OD5kOoeLwuxfUOhEl+iFg9WSaKXBVMwh/kkOH7OAcFq87k7Cuglycs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
