travis:
  secure:
    BINSTAR_TOKEN: N6o7V9A0YlcuJUdfYptZd0KfbgL0zOjA/ZI6Spqlg+iAaPa9yB/2KrIkMzzChJAGU4e5IXHSbznLz7SF1YXKSq5nXaexAbWqaN/zk34ItHti7O3RJVIj1uDZ5Bqywou4mzNRv1ZnqE4HRZCUtEaU+HGXFvYa1Tn/c6I0heBBk7gAIHWNMOxwWxP6mo8k0HTuiGlVL2xWpBMK47Y8kp6z+bM7jKV2L2V8HumTRkRXyqp2l/8+V9z0pvAB2U0brTm1mZSJQjkr0dL96/O23+Zd/PclqIW2z/uvjzew+r1A1b68V8Iyn6tzdFXYXyOUAQGxswOMl60jiM4ad9N8RPyzhRafgUbFQrTbcDkg3h5yDJMz2qo4tmH7PLcp3U6O/ZnpaGXlDOdl+PHA05Y4r8ZqUHIySNxWQZIhKQUPBZAkNkf2CstHXeDiuUMEYkmrsl25lnlwPCDGf7jpCvYtTdV24D2B5eTqTHenbRxAk7CZYNaxmqbTQuq5xUK8COPtW51skaLAbmMb13Lr1PvspB2f+tCCne7N81Il8CrmhFPSPkaLH5EAUgwO43pgk/6SkEINHba/Is6Njs2FdkNkAfVYOQT5VLzrm7+ESAvXRXrhY3vudagQAWCyOEs7ddUcYORdmDCoV+D9Kv/0L4SpwxF/KGT13EgBpmfhknK+nGCGfy0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
